keyBinding.1.turn-left=Q
keyBinding.1.turn-right=D
keyBinding.2.turn-left=LEFT
keyBinding.2.turn-right=RIGHT
keyBinding.3.turn-left=O
keyBinding.3.turn-right=P
keyBinding.4.turn-left=J
keyBinding.4.turn-right=K